spring:
  application:
    name: library-service

  datasource:
    url: jdbc:postgresql://localhost:5432/music_db
    username: postgres
    password: verystrongpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changelog: classpath:/db/music_db_changelog.yml

server:
  port: 8082