spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/music_auth_db
    username: postgres
    password: verystrongpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changelog: classpath:/db/changelog.yml

jwt:
  accessExpiration: 3600
  refreshExpiration: 86400
  jwtSecretKey: secretKey

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

eternalToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwicm9sZXMiOlsiQURNSU4iXSwiaXNFbmFibGVkIjp0cnVlLCJleHAiOjE2NzU2MDE2MjIsImlhdCI6MTU4OTIwMTYyMiwiZW1haWwiOiJhQG1haWwuY29tIn0.05SIH8oESRZmNASuR1TxmZ3YvatFAElLWKw01z4ijlR35tUNDIYzhYMHojSmzQk1DTsSQ2UsE3Kl9ABJqIDRcw