spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:postgresql://localhost:5432/music_db
    username: postgres
    password: verystrongpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changelog: classpath:/db/changelog.yml

server:
  port: 8083
jwt:
  jwtSecretKey: secretKey
upload:
#  path: /C:/Users/Munchausen/IdeaProjects/MusicSufferService/uploads
  path: /home/humanoid/IdeaProjects/uploads

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka