spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/music_files_db
    username: postgres
    password: verystrongpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

file:
  rootPath: /C:/Users/Munchausen/IdeaProjects/MusicSufferService/music_files