spring:
  application:
    name: gateway
  profiles:
    active: alone

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

api:
  userHost: http://localhost:8081
  libraryHost: http://localhost:8082
  adminHost: http://localhost:8083
  streamingHost: http://localhost:8084
  imageHost: http://localhost:8085

  allowedOrigins:
    - http://localhost:3000
    - http://127.0.0.1:3000